<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Paso 1: Importar Librerías</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Importamos <strong>folium</strong> para crear y visualizar mapas interactivos y <strong>pandas</strong> para manipular el conjunto de datos de los lanzamientos. También importamos plugins específicos de folium (MarkerCluster, MousePosition y DivIcon) que el laboratorio utiliza para agregar interactividad y marcadores personalizados.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">La celda debe ejecutarse de forma silenciosa e imprimir las versiones de las librerías. Al estar en tu entorno <code>decision-tools-312</code>, no debería requerir instalaciones adicionales. Verifica que pandas reporte la versión 3.0.3 y folium la 0.20.0.</p>
</div>

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #0f62fe; font-family: sans-serif;">
    <h3 style="color: #0f62fe; margin-top: 0;">Preparación del Entorno: Importación de Librerías</h3>
    <p><b>Qué hacemos:</b></p>
    <p>Importamos las dependencias principales para el análisis visual. <code>folium</code> nos permitirá generar mapas interactivos y <code>pandas</code> se encargará de la manipulación de datos. Además, cargamos complementos específicos de Folium (plugins) que utilizaremos en las próximas tareas para agrupar marcadores en zonas de alta densidad, capturar coordenadas con el cursor y personalizar los iconos de los sitios de lanzamiento.</p>
</div>

In [1]:
import folium
import pandas as pd
from folium.plugins import MarkerCluster
from folium.plugins import MousePosition
from folium.features import DivIcon

# Opcional para este paso, pero útil para confirmar tu entorno:
print(f"Pandas version: {pd.__version__}")
print(f"Folium version: {folium.__version__}")
print("Librerías importadas exitosamente.")

Pandas version: 3.0.3
Folium version: 0.20.0
Librerías importadas exitosamente.

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Importar Plugins de Folium</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Cargamos herramientas específicas de la librería folium. <strong>MarkerCluster</strong> nos permitirá agrupar marcadores que estén muy juntos, <strong>MousePosition</strong> mostrará las coordenadas dinámicas del cursor sobre el mapa, y <strong>DivIcon</strong> habilitará la creación de marcadores con texto personalizado mediante HTML.</p>

In [2]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster

# Import folium MousePosition plugin
from folium.plugins import MousePosition

# Import folium DivIcon plugin
from folium.features import DivIcon

print("Plugins de folium importados correctamente.")

Plugins de folium importados correctamente.

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Descargar y Leer el Dataset</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">El código original de IBM utiliza <code>js</code> y <code>fetch</code>, que son librerías exclusivas de entornos de navegador como JupyterLite o Pyodide. Dado que estás trabajando en tu entorno local <code>decision-tools-312</code>, adaptamos esta celda para leer el archivo CSV directamente desde la URL utilizando la función nativa <code>read_csv</code> de pandas, lo cual es más directo y compatible con Python 3.12.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">La celda descargará los datos y mostrará las primeras cinco filas del DataFrame <code>spacex_df</code>. Verifica que las columnas contengan información geográfica como <code>Lat</code>, <code>Long</code> y el nombre del sitio de lanzamiento.</p>
</div>

In [3]:
import pandas as pd

# URL del dataset proporcionado por IBM
URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'

# Leer el CSV directamente desde la URL usando pandas
spacex_df = pd.read_csv(URL)

# Mostrar las primeras filas para confirmar la carga exitosa
spacex_df.head()

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Filtrar y Agrupar Sitios de Lanzamiento</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Seleccionamos las columnas relevantes para nuestro análisis espacial: el nombre del sitio, sus coordenadas (latitud y longitud) y el estado del lanzamiento (class). A continuación, usamos <code>groupby</code> para obtener una lista única de los sitios de lanzamiento y sus coordenadas, tomando el primer registro de cada grupo.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">El resultado será un DataFrame pequeño que mostrará únicamente los sitios de lanzamiento únicos (usualmente 4) junto con sus valores de <code>Lat</code> y <code>Long</code>. Verifica que no haya sitios duplicados en esta tabla, ya que usaremos estas coordenadas exactas para colocar los marcadores en el mapa.</p>
</div>

In [4]:
# Select relevant sub-columns: `Launch Site`, `Lat`, `Long`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]

# Group by Launch Site to get unique coordinates
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()

# Keep only the columns needed for marking the map
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]

# Display the resulting dataframe
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Inicializar el Mapa Base</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Definimos las coordenadas del Centro Espacial Johnson de la NASA como nuestro punto de partida geográfico. Luego, utilizamos <code>folium.Map</code> para crear un objeto de mapa centrado en esa ubicación exacta, estableciendo un nivel de zoom inicial de 10.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">Al ejecutar esta celda, el objeto <code>site_map</code> se renderizará directamente en Jupyter. Deberías ver un mapa interactivo centrado en el área de Houston, Texas. Puedes desplazar el mapa y hacer zoom para comprobar que funciona correctamente antes de empezar a añadir los marcadores de lanzamiento.</p>
</div>

In [5]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]

# Initialize the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

# Display the map
site_map

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Agregar Marcadores al Mapa Base</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Añadimos dos elementos visuales a nuestro mapa en las coordenadas del Centro Espacial Johnson de la NASA. Primero, creamos un <code>folium.Circle</code> (un círculo de color naranja con un radio de 1000 metros) que incluye un mensaje emergente (popup). Segundo, creamos un <code>folium.map.Marker</code> que utiliza el plugin <code>DivIcon</code> para colocar el texto estático "NASA JSC" directamente sobre el mapa.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">Al ejecutar esta celda y llamar de nuevo a <code>site_map</code>, el mapa se actualizará. Deberías ver el área de la NASA resaltada con un círculo y la etiqueta de texto. Haz clic en el círculo para verificar que el popup funciona correctamente.</p>
</div>

In [6]:
# Create a colored circle at NASA Johnson Space Center's coordinate with a popup label
circle = folium.Circle(
    nasa_coordinate, 
    radius=1000, 
    color='#d35400', 
    fill=True
).add_child(folium.Popup('NASA Johnson Space Center'))

# Create a marker with a custom icon showing its name as a text label
marker = folium.map.Marker(
    nasa_coordinate,
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
    )
)

# Add both the circle and the text marker to the map
site_map.add_child(circle)
site_map.add_child(marker)

# Display the updated map
site_map

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Tarea 1: Marcar todos los sitios de lanzamiento</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Reiniciamos el mapa con un nivel de zoom menor (5) para obtener una vista continental. Luego, implementamos un bucle <code>for</code> que itera sobre cada fila del DataFrame <code>launch_sites_df</code>. Por cada sitio de lanzamiento, extraemos sus coordenadas (Latitud y Longitud) y agregamos dinámicamente un círculo con un popup y un marcador de texto utilizando la misma técnica aplicada previamente para el centro de la NASA.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">El mapa actualizado mostrará marcadores naranjas para todos los sitios de lanzamiento presentes en el dataset. Al observar el mapa, podrás empezar a identificar patrones geográficos comunes, como su proximidad a la costa o su ubicación relativa al ecuador.</p>
</div>

In [7]:
# Initialize the map with a wider zoom to see all of the US
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. 
# In addition, add Launch site name as a popup label
for index, row in launch_sites_df.iterrows():
    # Coordenadas actuales del bucle
    site_coordinate = [row['Lat'], row['Long']]
    site_name = row['Launch Site']
    
    # Crear un círculo coloreado
    circle = folium.Circle(
        site_coordinate, 
        radius=1000, 
        color='#d35400', 
        fill=True
    ).add_child(folium.Popup(site_name))
    
    # Crear un marcador con el nombre del sitio
    marker = folium.map.Marker(
        site_coordinate,
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % site_name,
        )
    )
    
    # Añadir los elementos al mapa
    site_map.add_child(circle)
    site_map.add_child(marker)

# Display the map
site_map

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Tarea 2: Preparar la Agrupación de Marcadores</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Revisamos las últimas 10 filas del DataFrame original para identificar la columna <code>class</code>, la cual indica el resultado del lanzamiento (1 para éxito, 0 para fallo). Como hay decenas de lanzamientos que ocurren exactamente en las mismas 4 coordenadas, creamos un objeto <code>MarkerCluster</code>. Este plugin de folium se encargará de agrupar visualmente los marcadores que se superponen, mostrando un número consolidado que se expande al hacer zoom.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">Verás la tabla con los últimos 10 registros de la base de datos y un mensaje confirmando que el agrupador fue creado en memoria. Revisa la columna <code>class</code> para confirmar los valores binarios (0 y 1).</p>
</div>

In [8]:
from IPython.display import display

# Mostrar las últimas 10 filas para inspeccionar los datos, especialmente la columna 'class'
display(spacex_df.tail(10))

# Crear un objeto MarkerCluster para manejar marcadores superpuestos
marker_cluster = MarkerCluster()

print("\nObjeto MarkerCluster creado exitosamente en memoria.")

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Objeto MarkerCluster creado exitosamente en memoria.

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Asignar Colores a los Marcadores</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Definimos una función en Python que evalúa el resultado de un lanzamiento. Si el valor es 1 (éxito), devuelve 'green'; si es 0 (fallo), devuelve 'red'. Utilizaremos el método <code>apply</code> de pandas para ejecutar esta función sobre la columna <code>class</code> y almacenar los resultados en una nueva columna llamada <code>marker_color</code> dentro de nuestro DataFrame <code>spacex_df</code>.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">La celda mostrará las últimas 10 filas del DataFrame actualizado. Verifica que la nueva columna <code>marker_color</code> se haya creado correctamente al final de la tabla y que sus colores ('green' o 'red') correspondan lógicamente con los valores de la columna <code>class</code> (1 o 0).</p>
</div>

In [9]:
# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red

def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'
    
# Create a new column in spacex_df dataframe called marker_color
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)

# Check the tail of the dataframe to confirm the new column
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1        green
47    KSC LC-39A  28.573255 -80.646895      1        green
48    KSC LC-39A  28.573255 -80.646895      1        green
49  CCAFS SLC-40  28.563197 -80.576820      1        green
50  CCAFS SLC-40  28.563197 -80.576820      1        green
51  CCAFS SLC-40  28.563197 -80.576820      0          red
52  CCAFS SLC-40  28.563197 -80.576820      0          red
53  CCAFS SLC-40  28.563197 -80.576820      0          red
54  CCAFS SLC-40  28.563197 -80.576820      1        green
55  CCAFS SLC-40  28.563197 -80.576820      0          red

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Agregar Marcadores de Lanzamiento al Agrupador</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Primero, vinculamos nuestro objeto <code>marker_cluster</code> al mapa principal. Luego, usamos un bucle <code>for</code> para recorrer cada registro (lanzamiento) en nuestro DataFrame <code>spacex_df</code>. Por cada lanzamiento, creamos un <code>folium.Marker</code> en sus coordenadas exactas, asignándole un icono cuyo color interno (<code>icon_color</code>) lee dinámicamente la columna <code>marker_color</code> que creamos en el paso anterior. Finalmente, añadimos cada marcador al agrupador en lugar de agregarlo directamente al mapa.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">Al visualizar el mapa, notarás círculos con números en las ubicaciones de los sitios de lanzamiento. Estos números indican la cantidad total de lanzamientos en esa área. Si haces clic en los agrupadores o haces zoom sobre ellos, se expandirán para revelar los marcadores individuales: verdes para los lanzamientos exitosos y rojos para los fallidos.</p>
</div>

In [10]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed
for index, record in spacex_df.iterrows():
    # Create a Marker with its coordinate
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        # Customize the Marker's icon property
        icon=folium.Icon(color='white', icon_color=record['marker_color']),
        # Adding a popup with the launch site name for better UX (optional but helpful)
        popup=f"Site: {record['Launch Site']}\nClass: {record['class']}"
    )
    # Add the marker to the cluster
    marker_cluster.add_child(marker)

# Display the map
site_map

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Inicio de la Tarea 3: Calcular Distancias</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">En la Tarea 3 medimos la proximidad de los sitios de lanzamiento a lugares clave para identificar patrones de seguridad y logística.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">Las celdas siguientes definen <code>calculate_distance</code> y calculan la distancia del sitio de lanzamiento a la costa, la autopista, el ferrocarril y la ciudad más cercanos, marcando cada una en el mapa.</p>
</div>

In [11]:
# Create a JavaScript formatter for the coordinates
formatter = "function(num) {return L.Util.formatNum(num, 5);};"

# Initialize the MousePosition plugin
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

# Add the mouse position tool to the existing map
site_map.add_child(mouse_position)

# Display the map with the new tool
site_map

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Función para Calcular Distancias</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Importamos funciones matemáticas estándar y definimos la función <code>calculate_distance</code>, la cual aplica la fórmula de Haversine. Esta fórmula nos permite calcular la distancia en línea recta (en kilómetros) entre dos puntos en una esfera, dadas sus latitudes y longitudes. Es totalmente compatible con tu entorno de Python 3.12.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">La celda se ejecutará de forma silenciosa y el mensaje de confirmación aparecerá abajo. Esto significa que la función quedó guardada en la memoria, lista para ser utilizada en el siguiente paso cuando elijamos un punto de interés.</p>
</div>

In [12]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

print("Función calculate_distance definida exitosamente en memoria.")

Función calculate_distance definida exitosamente en memoria.

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Calcular Distancia a la Costa y Agregar Marcador</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Tomamos las coordenadas de un sitio de lanzamiento específico (por ejemplo, CCAFS SLC-40) y las coordenadas de la costa más cercana provistas en el código de ejemplo de IBM. Utilizamos la función <code>calculate_distance</code> previamente en memoria para obtener la distancia exacta en kilómetros. Finalmente, creamos un marcador en el punto costero que muestra textualmente dicha distancia utilizando un <code>DivIcon</code>.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">La celda imprimirá la distancia calculada (aproximadamente 0.51 km) y mostrará el mapa. En la costa cercana al sitio CCAFS SLC-40, deberías ver un nuevo marcador de texto en color naranja indicando la distancia exacta. Verifica que el marcador aparece en la ubicación correcta al este del sitio de lanzamiento.</p>
</div>

In [13]:
# Usaremos las coordenadas del sitio de lanzamiento CCAFS SLC-40 como ejemplo
launch_site_lat = 28.563197
launch_site_lon = -80.576820

# Coordenadas de la costa más cercana medidas con MousePosition
coastline_lat = 28.5638
coastline_lon = -80.56818

# Calcular la distancia usando la función definida en el paso anterior
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
print(f"Distancia calculada a la costa: {distance_coastline:.2f} km")

# Crear y añadir un marcador en el punto costero que muestre la distancia
distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_coastline),
    )
)

site_map.add_child(distance_marker)

# Mostrar el mapa actualizado
site_map

Distancia calculada a la costa: 0.85 km

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Dibujar una Línea (PolyLine) hacia la Costa</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Siguiendo las instrucciones del laboratorio de IBM, ahora trazaremos una línea recta entre el sitio de lanzamiento y el punto costero seleccionado. Para ello, agrupamos las coordenadas de ambos puntos en una lista y utilizamos <code>folium.PolyLine</code> para generar la línea visual. Finalmente, la agregamos a nuestro mapa base.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">Al visualizar el mapa interactivo, deberías ver una delgada línea azul que conecta el centro del sitio de lanzamiento CCAFS SLC-40 directamente con el marcador naranja en la costa (el cual indica la distancia calculada anteriormente). Confirma que la línea une ambos puntos con precisión.</p>
</div>

In [14]:
# Crear una lista con las coordenadas del sitio de lanzamiento y la costa
coordinates = [
    [launch_site_lat, launch_site_lon],
    [coastline_lat, coastline_lon]
]

# Crear un objeto folium.PolyLine usando las coordenadas
lines = folium.PolyLine(
    locations=coordinates, 
    weight=2,        # Aumentamos ligeramente el grosor para mejor visibilidad
    color='blue'     # Definimos el color de la línea
)

# Añadir la línea al mapa
site_map.add_child(lines)

# Mostrar el mapa actualizado
site_map

<div style="background-color: #f4f6f7; padding: 15px; border-left: 5px solid #005a9c; border-radius: 5px; font-family: sans-serif;">
    <h2 style="margin-top: 0; color: #005a9c;">Marcar un Punto de Interés y Trazar Ruta</h2>
    <h3 style="color: #333333;">Qué hacemos</h3>
    <p style="color: #555555;">Basado en las instrucciones de tu laboratorio de IBM, ahora aplicaremos la misma lógica para calcular la distancia a otro punto geográfico cercano (como una autopista, vía férrea o ciudad). Seleccionaremos coordenadas aproximadas para una autopista cercana al sitio CCAFS SLC-40. Calcularemos la distancia, colocaremos un marcador con el texto en verde y dibujaremos una nueva línea (<code>folium.PolyLine</code>) para conectarlos.</p>
    <h3 style="color: #333333;">Qué observar</h3>
    <p style="color: #555555;">La celda mostrará la distancia calculada en texto y renderizará el mapa. Verás una nueva línea de color verde que conecta el sitio de lanzamiento con el punto de la autopista, junto con su respectivo marcador indicando la distancia. Esto ayuda a evaluar la proximidad de infraestructuras críticas al sitio de lanzamiento.</p>
</div>

In [15]:
# Coordenadas aproximadas de una autopista cercana (Samuel C. Phillips Pkwy)
highway_lat = 28.56324
highway_lon = -80.57076

# Asumimos que launch_site_lat y launch_site_lon (CCAFS SLC-40) siguen en memoria
# launch_site_lat = 28.563197
# launch_site_lon = -80.576820

# 1. Calcular la distancia
distance_highway = calculate_distance(launch_site_lat, launch_site_lon, highway_lat, highway_lon)
print(f"Distancia calculada a la autopista: {distance_highway:.2f} km")

# 2. Crear y añadir un marcador de distancia
distance_marker_highway = folium.Marker(
    [highway_lat, highway_lon],
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12; color:#27ae60;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_highway),
    )
)
site_map.add_child(distance_marker_highway)

# 3. Dibujar la línea entre el sitio y la autopista
highway_coordinates = [
    [launch_site_lat, launch_site_lon],
    [highway_lat, highway_lon]
]

lines_highway = folium.PolyLine(
    locations=highway_coordinates, 
    weight=2,
    color='green'
)
site_map.add_child(lines_highway)

# Mostrar el mapa actualizado
site_map

Distancia calculada a la autopista: 0.59 km

In [16]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Coordenadas aproximadas del ferrocarril más cercano (NASA Railroad)
railway_lat = 28.57114
railway_lon = -80.58528

# Asumimos que launch_site_lat y launch_site_lon (CCAFS SLC-40) siguen en memoria
distance_railway = calculate_distance(launch_site_lat, launch_site_lon, railway_lat, railway_lon)
print(f"Distancia calculada al ferrocarril: {distance_railway:.2f} km")

distance_marker_railway = folium.Marker(
    [railway_lat, railway_lon],
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12; color:#8e44ad;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_railway),
    )
)
site_map.add_child(distance_marker_railway)

# Draw a line between the marker to the launch site
railway_coordinates = [
    [launch_site_lat, launch_site_lon],
    [railway_lat, railway_lon]
]

lines_railway = folium.PolyLine(
    locations=railway_coordinates,
    weight=2,
    color='purple'
)
site_map.add_child(lines_railway)

# Mostrar el mapa actualizado
site_map

Distancia calculada al ferrocarril: 1.21 km

In [17]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Coordenadas de la ciudad más cercana (Melbourne, FL)
city_lat = 28.10469
city_lon = -80.64784

distance_city = calculate_distance(launch_site_lat, launch_site_lon, city_lat, city_lon)
print(f"Distancia calculada a la ciudad: {distance_city:.2f} km")

distance_marker_city = folium.Marker(
    [city_lat, city_lon],
    icon=DivIcon(
        icon_size=(20, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12; color:#c0392b;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_city),
    )
)
site_map.add_child(distance_marker_city)

# Draw a line between the marker to the launch site
city_coordinates = [
    [launch_site_lat, launch_site_lon],
    [city_lat, city_lon]
]

lines_city = folium.PolyLine(
    locations=city_coordinates,
    weight=2,
    color='red'
)
site_map.add_child(lines_city)

# Mostrar el mapa actualizado
site_map

Distancia calculada a la ciudad: 51.47 km